on:
  push:
    branches:
      - master
name: Package Checking
jobs:
  checkBuildAndSize:
    name: Build & Check Size
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install
        run: yarn install
      - name: Test
        run: yarn test
        env:
          CI: true
      - name: Build
        run: yarn build
      - name: Check Package Size
        run: yarn checksize
